### ISSUE TITLE
GETADDRESSBYACCOUNT RPC returning empty list depsite being having multiple addresses associated to an IGUANA account

### ISSUE THREAD

**Issue by kashifali007** [jl777/SuperNET#34]
here is the somepart of the dumpwallet file that you can see the addresses belongs to IGUANA account

"IGUANA":{"19405d0cbeeb34a70fae0428497775d8d8357030":"d45ecaeb08fbb94eeb3b32de785958b0bc63b42373b7fe84452c7218683b1386","e2a2186135770d59280c28666829c9e9e3de9fa7":"2c2d00a06adf8baf4adefab74c12f86615325fea9cde1651f78850b5f5645ba2","87b79643c0895de570fe1d014cbbdcf6086bde03":"7a5a0179e62842181b5e3c32f78e19ca6fb10f32932794d3a938590b1afe93f3","e6ac80a8db27a3991a36c478618893c4fd1bb117":"8a065016977fe061697436aa737930e4579ece7f1fe6defbd8bccc572113a5ae","bde7f829f35be68ae6652de6af9a96b5ad1f2694":"67fbd5f3707b83ff8850b49dea7be6bb64e16ca9dd8d3ab4b58cd3f24b129a9f","77dfd58fdee7643f4a812203e05b28739d89ded8":"919ad7b0fa17e1b7deceab420462192e2c5efc7e867862803611b11366f69ac2","2d30ec68a9bb4f547956ee0f7b1873454b501d64":"ffd7c1987f31a9c630c3db276458b04d03f88319cd83b1b97ccde472a66f6555","ebff1d001d3314b21b2deefe1cce8e80ab3d392d":"29c28bc64912d096ef166b95760d1b0aabb51ed0c7b4e2725c3a0ca080326f9f","c999aa19d8172a0b52d1c49044e4e78ccec41414":"e05daaab941464f7329c66860fbec7018968bd6af7d8d664b8385204f5c3bac0","f6407980a8fbab82cc4859368f1484954fd7969b":"df5cec10c7afa87b33011c9c94bd6a70575e7d9046d1879c4d8d559c05abfca1","1ff760309b0ec38ad8eb21cea806bf16928db48a":"e7afd9319bc47e435bee6d1157cd494c9a412d9d6058aaef79542eff5a9e66aa","367edcd5884c5cb11ee43840233f7f3205bf7483":"bc0fe5b9393b4b2fbce2e9f5d1701ad9e4eb28ffbe4b40c992418daa24608dd7","35e7408f9df641a655fea39c156b95911c9763e5":"e8881aee74c308c292582a9d650f35b5a4ddff05b66a5afe049b1829da487e0b","4d4c74cd57f9cf56c0ca3c9f5989092a8086929e":"85933b1ef38b8c6a9a238f0c034e763b753643cc159e7f0e7ad8a8cbd80f4894","8d01194b8880189bc8d3e606f13fbb5643af0d80":"835558c182fc9c21cd4b5cd1d3fefa814d387177bed159ca97b786bbb97cda36","eb27da66fb89a9831ee8376cff6d34827179830f":"b062bf6e247b78f630d7e1c83b9d418554bbf5d7664feec5ebad7c43b2e549f1","0c54a561d3917956c512fbb7f22b60853484edb8":"88e973859c92b4a7891189ca9f25e261959beb97ab27f572c99b537e8a5c359e","873dc351a679c0bbe0e5890c7c336f52f4a98cd5":"a88f3d4b42f846515192e8acdf5b62c2447d5d4ac3de7a5f3c76d0ec11b8f15b"},"check":{"6a47e4d6ecd6c5bd4f971abf0e86c9ece26c9b31":"c19dafe3563e14d08d75f44fb130e374fd90f5006c1e0c921e74389383635232"},"bug":{"c7e1df533ecdb5f1af85dc19808d05fc00db5ca5":"a6fbf39459fcd6311aed88472e6f48659ae9f6bfd04bffe20456c9a37a21a0b9"}},"tag":"15103772134764966586"}

**Comment by jl777** [comment]
I cant duplicate this with the latest version. please make a specific series of curl commands from a clean state that reproduces the bug.

**Comment by kashifali007** [comment]
getaccountbyaddress still returning the empty list. atleast should return one address

[11:21]  
./getaddressbyaccount_WVN 
{"result":[],"tag":"5671816449915483967"}

[11:22]  
curl -s --url "http://127.0.0.1:7778" --data "{\"agent\":\"iguana\",\"method\":\"addcoin\",\"newcoin\":\"BTCD\",\"services\":0,\"portp2p\":14631}"

[11:23]  
curl -s --url "http://127.0.0.1:7778" --data "{\"agent\":\"bitcoinrpc\",\"method\":\"getaccountaddress\",\"account\":\"IGUANA\"}"

[11:23]  
curl --url "http://127.0.0.1:7778" --data "{\"agent\":\"bitcoinrpc\",\"method\":\"getaddressesbyaccount\",\"account\":\"IGUANA\"}"
echo ""

**Comment by kashifali007** [comment]
Resolved-fixed and verified. 
Closing it
Thanks,
-Kashif Ali
