### ISSUE TITLE
RPC sendtoaddress yielding "error":"need address and amount" despite with right parameters

### ISSUE THREAD

**Issue by kashifali007** [jl777/SuperNET#35]
{"error":"need address and amount","tag":"9475812516810586895"}

curl --url "http://127.0.0.1:7778"  --data "{\"method\":\"sendtoaddress\",\"params\":[\"RMcHHn9RtkdtgVHiCxysrG8q2EQTYiJfRT\", 10.000]}"

**Comment by kashifali007** [comment]
./listaccount_ALL 
{"result":{"default":140.42070000,"RPCtesting":140.42070000,"change":140.42070000,"RPCtest_2":140.42070000,"RPCtesting_2":140.42070000,"RPCtest2":140.42070000,"kashif":140.42070000,"IGUANA":140.42070000,"check":140.42070000,"bug":140.42070000},"tag":"17094416341926256476"}

**Comment by kashifali007** [comment]
send amount to IGUANA

**Comment by kashifali007** [comment]
This issue could be the wrong balance being displayed by listaccount RPC but not sure. I've also tried with amount=0.004 producing same results.

**Comment by jl777** [comment]
a wallet that is messed up wont work right, especially sending. there is already an issue with the messed up wallet so I will close this one

**Comment by kashifali007** [comment]
Alright
