### ISSUE TITLE
RPC LISTRECEIVEDBYACCOUNT is showing wrong confirmations

### ISSUE THREAD

**Issue by kashifali007** [jl777/SuperNET#37]
RPC LISTRECEIVEDBYACCOUNT is showing wrong confirmations against all accounts.

./listreceivedbyaccount 
{"result":[{"account":"default","amount":0,"confirmations":10}, {"account":"RPCtesting","amount":0,"confirmations":10}, {"account":"change","amount":0,"confirmations":10}, {"account":"RPCtest_2","amount":0,"confirmations":10}, {"account":"RPCtesting_2","amount":0,"confirmations":10}, {"account":"RPCtest2","amount":0,"confirmations":10}, {"account":"kashif","amount":0,"confirmations":10}, {"account":"IGUANA","amount":0,"confirmations":10}, {"account":"check","amount":0,"confirmations":10}, {"account":"bug","amount":0,"confirmations":10}],"tag":"152711271757487891

**Comment by jl777** [comment]
i removed the confirmations field, it seems a lot of work just to implement this for now

**Comment by jl777** [comment]
closed as a wont implement unless there is great need for this field
