### ISSUE TITLE
RPC listlockunspent returning just the tag(LOW PRIORITY: not implemented fully)

### ISSUE THREAD

**Issue by kashifali007** [jl777/SuperNET#39]

**Comment by kashifali007** [comment]
/listlockunspent 
{"result":[],"tag":"9000210378947336552"}

curl --url "http://127.0.0.1:7778" --data "{\"agent\":\"bitcoinrpc\",\"method\":\"listlockunspent\"}"

**Comment by kashifali007** [comment]
As per my discussion with James that will be implemented later

**Comment by jl777** [comment]
this is not on the list of musthave RPC, closed for now
