### ISSUE TITLE
RPC WALLETPASSPHRASECHANGE returning error 

### ISSUE THREAD

**Issue by kashifali007** [jl777/SuperNET#43]
RPC WALLETPASSPHRASECHANGE returning error 

steps to reproduce:
curl -s --url "http://127.0.0.1:7778" --data "{\"agent\":\"bitcoinrpc\",\"method\":\"encryptwallet\",\"passphrase\":\"Admin123@\"}"

curl -s --url "http://127.0.0.1:7778" --data "{\"agent\":\"bitcoinrpc\",\"method\":\"walletpassphrasechange\",\"oldpassword\":\"Admin123@\",\"newpassword\":\"Admin123456@\",\"oldpermanentfile\":\"\",\"permanentfile\":\"\"}"

RESULTS:
./walletpassphraseChange 
{"error":"error changing walletpassphrase","tag":"18157287915569421321"}

**Comment by kashifali007** [comment]
the issue is still there on fresh wallet as well

**Comment by jl777** [comment]
not the best solution, but if you call it again it seems to work. I changed the error message to indicate this

**Comment by kashifali007** [comment]
verified-fixed; so closing it
