### ISSUE TITLE
Leapsecond missing 2016 December 31, 23h 59m 60s

### ISSUE THREAD

**Issue by CHMEX** [jl777/SuperNET#523]
https://github.com/jl777/SuperNET/blob/master/crypto777/OS_time.c#L303

LINE: 303

char *leapseconds[] = { "+1972-06-30", "+1972-12-31", "+1973-12-31", "+1974-12-31", "+1975-12-31", "+1976-12-31", "+1977-12-31", "+1982-06-30", "+1983-06-30", "+1985-06-30", "+1987-12-31", "+1989-12-31", "+1990-12-31", "+1992-06-30", "+1993-06-30", "+1994-06-30", "+1995-12-31", "+1997-06-30", "+1998-12-31", "+2005-12-31", "+2008-12-31", "+2012-06-30", "+2015-06-30" };

**I'm not sure if this is important or not for stability feel free to close issue immediately if it can be ignored.**

There was a lap second in 2016 which is not part of the array.

Details:
ftp://hpiers.obspm.fr/iers/bul/bulc/bulletinc.52

******
 A positive leap second will be introduced at the end of December 2016.
 The sequence of dates of the UTC second markers will be:		
		
                          2016 December 31, 23h 59m 59s
                          2016 December 31, 23h 59m 60s
                          2017 January   1,  0h  0m  0s
              
 The difference between UTC and the International Atomic Time TAI is:

  from 2015 July 1, 0h UTC, to 2017 January 1 0h UTC   : UTC-TAI = - 36s
  from 2017 January 1, 0h UTC, until further notice    : UTC-TAI = - 37s 

*****

**Comment by jl777** [comment]
it is an off by a second issue if these functions are relied on. I dont, but might as well fix it.

pushed fix in 2e9f7e89d3eb3737dbd6374a71ce93bdfb6b82b0
