### ISSUE TITLE
call to getaccountaddress rpc each time doesn't generate new address

### ISSUE THREAD

**Issue by kashifali007** [jl777/SuperNET#53]
Once a payment has been received to an address generated by getaccountaddress rpc, future calls to this RPC for the same account will return a different address.

if that is the case we would need to send payment to that address. once the payment is done on that address then we would need to re-execute that rpc again to check that if its account to different address or not

currently I'm getting the same address 
everytime

**jl777 [9:51 PM]**  
ok, that is not implemented and not an quick fix. plz make github issue for this for now

**for reference:**
kashif@ubuntu:~/tests$ ./getaccountaddress_WVA 
{"address":"RQCP1TcfevTQU35ZftPNx2TZpB9ZkSZQ3S","rmd160":"a3a0ee4fc2455ed9e1d57ef87dac45513f8a5441","coin":"BTCD","pubkey":"02c38bea4010d53e9d2b5079cbe402f6e59e8e1ad082caab6becd2102229259a8b","account":"IGUANA","result":"success","tag":"5517568018868714116"}
kashif@ubuntu:~/tests$ 
kashif@ubuntu:~/tests$ 
kashif@ubuntu:~/tests$ 
kashif@ubuntu:~/tests$ ./getaccountaddress_WVA 
{"address":"RQCP1TcfevTQU35ZftPNx2TZpB9ZkSZQ3S","rmd160":"a3a0ee4fc2455ed9e1d57ef87dac45513f8a5441","coin":"BTCD","pubkey":"02c38bea4010d53e9d2b5079cbe402f6e59e8e1ad082caab6becd2102229259a8b","account":"IGUANA","result":"success","tag":"5230806884385881920"}
kashif@ubuntu:~/tests$ 
kashif@ubuntu:~/tests$ 
kashif@ubuntu:~/tests$ 
kashif@ubuntu:~/tests$ 
kashif@ubuntu:~/tests$ ./getaccountaddress_WVA 
{"address":"RQCP1TcfevTQU35ZftPNx2TZpB9ZkSZQ3S","rmd160":"a3a0ee4fc2455ed9e1d57ef87dac45513f8a5441","coin":"BTCD","pubkey":"02c38bea4010d53e9d2b5079cbe402f6e59e8e1ad082caab6becd2102229259a8b","account":"IGUANA","result":"success","tag":"18104098791181749538"}

**sequence of curl:**
curl -s --url "http://127.0.0.1:7778" --data "{\"agent\":\"iguana\",\"method\":\"addcoin\",\"newcoin\":\"BTCD\",\"services\":0,\"portp2p\":14631}"
curl -s --url "http://127.0.0.1:7778" --data "{\"agent\":\"bitcoinrpc\",\"method\":\"walletpassphrase\",\"password\":\"YOURPASSWORD\",\"timeout\":300}"
curl -s --url "http://127.0.0.1:7778" --data "{\"agent\":\"bitcoinrpc\",\"method\":\"getaccountaddress\",\"account\":\"IGUANA\"}"
curl -s --url "http://127.0.0.1:7778" --data "{\"agent\":\"bitcoinrpc\",\"method\":\"getaccountaddress\",\"account\":\"IGUANA\"}"
curl -s --url "http://127.0.0.1:7778" --data "{\"agent\":\"bitcoinrpc\",\"method\":\"getaccountaddress\",\"account\":\"IGUANA\"}"

**Comment by kashifali007** [comment]
Currently I can't say that rpc is not working fine until we are able to send payment to address generated by that rpc. we need to fix sendtoaddress rpc first then this rpc will be test properly.

**Comment by kashifali007** [comment]
confirmed its a bug. 
Did transaction to the address mentioned in above comment and when I re-executed the same rpc the newly generated address was same as previous one.

Thanks,
-Kashif Ali

**Comment by jl777** [comment]
pushed a possible fix, please confirm if it is working properly. there might be 10 to 30 seconds delay in noticing funds has arrived

**Comment by jl777** [comment]
this has been fixed
