### ISSUE TITLE
Owner of INSTANTDEX_RMD160 can costlessly attempt to steal?

### ISSUE THREAD

**Issue by treygriffith** [jl777/SuperNET#553]
Hi,

I was looking at the way Atomic Swaps work in BarterDEX to include it as a working implementation on swapready.net, and wanted to make sure I understand the type of atomic swaps that are being done, which is different from the pure CLTV style I've seen before.

If I understand:

1. Alice and Bob pay a fee amounting to 1/777 of the transaction size to INSTANTDEX_RMD160 to disincentivize cheating at step 2.
2. Alice and Bob each generate 1000 private/public key pairs, and hashes of the private keys. They exchange the hashes and public keys for all 1000.
3. Alice and Bob each select one of the others' public keys/hashes, and their counterparty provides the private keys corresponding to the 999 other public keys/hashes.
4. Alice and Bob verify that the private keys provide correspond to the public keys and hashes provided in step 2.
5. If either discovers a bad pair, that indicates an attempt at cheating, and abandons the transaction, leading both to lose their fees.
6. Bob creates a deposit (using the coin that supports CLTV) that he can reclaim by revealing the private key selected by Alice, or Alice can claim after the expiration period.
7. Alice creates a payment to a multi-sig address corresponding to the selected private keys for both Bob and Alice.
8. Bob creates that can be claimed using Alice's private key, or reclaimed by Bob after an expiration period (shorter than the one in step 6).
9. Alice claims the payment in step 8, revealing her private key.
10. Bob claims the payment in step 7, using Alice's revealed private key and his private key.
11. Bob reclaims his deposit in step 6.

Now Alice, if she's a bad actor, can create her 1000 private/public key pairs and hashes such that 1 out of the 1000 does not match, and in so doing, steal from Bob. But since this has a 0.1% chance of success, and she's paid a 0.13% fee to the DEX, this would be unprofitable.

But what if Alice also controls INSTANTDEX_RMD160? Then Alice can continue with the 0.1% chance of success at stealing the entire trade but without any cost (because she can retrieve her own insurance fee).

Is there a mechanism to discourage or prevent this abuse by the owner of INSTANTDEX_RMD160?

**Comment by satindergrewal** [comment]
These raw drafts of whitepapers might also be helpful as reference:
https://github.com/SuperNETorg/komodo/wiki/barterDEX-Whitepaper-v2
https://github.com/SuperNETorg/komodo/wiki/dICO-Whitepaper
https://github.com/SuperNETorg/komodo/wiki/Delayed-Proof-of-Work-(dPoW)-Whitepaper

There are more refined and content-rich whitepapers done by the team as well, can see it's draft here, which is soon to be available on website: https://docs.google.com/document/d/1SWT-Dk9nFo79P_PdCXQ8OvNQ5kSXcbYCTols7HG8eMs

**Comment by treygriffith** [comment]
None of those have to do with BarterDEX except for the BarterDEX whitepaper, right? And that draft has been superseded by [v0.4](https://www.komodoplatform.com/en/technology/whitepapers/BarterDEX-Whitepaper-v0.4.pdf) hasn't it?

**Comment by jl777** [comment]
There is economic disincentive for the owner of INSTANTDEX_RMD160 to attack and that is doing so will greatly devalue the barterDEX. The DEX coin owns that RMD160 and stealing funds using the 1:1000 attack first of all would be quite challenging to do and counterproductive.

I dont expect this attack to surface in the wild as it is uneconomic

**Comment by satindergrewal** [comment]
@treygriffith the whitepaper(s) recently updated by the marketing team. Latest here: https://www.komodoplatform.com/en/technology/whitepapers/2018-01-13-Komodo-White-Paper-Full.pdf

**Comment by treygriffith** [comment]
@jl777 what does it mean to say that "the DEX coin owns that RMD160"?

It is true that as long as the owner of INSTANTDEX_RMD160 considers barterDEX a going concern that they will likely consider the promise of future fees to be greater than the possible near-term gain from theft. However, if the owner of INSTANTDEX_RMD160 does not believe that (e.g. if they are an attacker) than they have no such incentive, and instead have an incentive to extract as much value as possible before they are discovered.

**Comment by jl777** [comment]
if you really believe that I will attack users of DEX just to make some money, then please dont use it

**Comment by treygriffith** [comment]
@jl777 I'm not saying that I believe that you will attack the DEX. I'm pointing out a vulnerability that exists in the protocol that makes it not a trustless atomic swap. If there is something I'm not understanding about it, please let me know.

**Comment by jl777** [comment]
An uneconomic attack vector isnt much of an attack vector. I claim that is it not an economically advantaged attack for me to attack my own system. We can agree to disagree and you can ignore that it is an attack with the expectation of a large financial and reputation loss.

Are you just trying to find some microscopic flaw? If so, I guess you found one. There is an uneconomic attack vector, it seems two of them. If this is the worst attack vectors against the system, it seems a practical solution that is miles ahead of anything else

**Comment by treygriffith** [comment]
@jl777 again, I'm not suggesting that you would attack your own system, because I agree that a scenario in which it would be economical to you is hard to imagine.

However, an attacker with access to INSTANTDEX_RMD160 for a limited period of time, say 24 hours before they assume they are caught, has an incentive to gain as much as possible in that limited period of time. Attempting to steal from traders is one such way that they can gain during that period.

I'm not trying to find a microscopic flaw, I'm trying to establish whether the methodology used by the DEX is a trustless atomic swap. It seems that it is close, but it is not quite trustless, as it has a small attack vector related to the insurance fee.

I agree that it is far ahead of most other exchanges in terms of minimizing trust and possible losses from a security breach.

**Comment by jl777** [comment]
yes, an unnoticed security breach would allow a onetime attack event, which in turn would need to be not noticed as it is being conducted and the amount able to be stolen is approx the dexfees of the attack swaps.

A contingency for this is to refund from past dexfees collected, any losses incurred, which if the service is running for any meaningful period of time, wont be an issue. So we are (sufficiently) self-insured against the only known attack vector.

**Comment by treygriffith** [comment]
Understood, thanks for engaging on the topic @jl777.
