### ISSUE TITLE
SETACCOUNT RPC doesn't associate the address to an account

### ISSUE THREAD

**Issue by kashifali007** [jl777/SuperNET#56]
SETACCOUNT RPC doesn't associate the address to an account.

RQK4mc7ZySXtQ6EweC4r2fcCdBTvsZqDc6 
now when i try to set that address to IGUANA_CHANGE account using setaccount rpc curl --url "http://127.0.0.1:7778" --data "{\"method\":\"setaccount\",\"params\":[\"RQK4mc7ZySXtQ6EweC4r2fcCdBTvsZqDc6\", \"IGUANA_CHANGE\"]}"
rpc returned with status sucess but the address isn't connected with account. In order to make sure that the address was associated correctly, executed getaddressbyaccount rpc curl --url "http://127.0.0.1:7778" --data "{\"agent\":\"bitcoinrpc\",\"method\":\"getaddressesbyaccount\",\"account\":\"IGUANA_CHANGE\"}"
but i found that the address wasn't associated.

here is the result of getaddressbyaccount rpc

./getaddressbyaccount_WVN 
{"result":["RSPpBwKyUerKttuo8s4nGDvJiG2TYBpaC1", "RNd62UYmMcncxmREXLWLqpDd45aTJQkVdx", "RWz1hjUawcERrKUR6CyF28aJjYudYa1mrn", "RLbuYWNHCp8gjcvjG6mHjrj9Nw7LZwGnVp"],"tag":"17793352264303860810"}

see set account didn't set the address the remaining amount address to IGUANA_CHANGE account

and these addresses :["RSPpBwKyUerKttuo8s4nGDvJiG2TYBpaC1", "RNd62UYmMcncxmREXLWLqpDd45aTJQkVdx", "RWz1hjUawcERrKUR6CyF28aJjYudYa1mrn", "RLbuYWNHCp8gjcvjG6mHjrj9Nw7LZwGnVp"] i didn't set them to IGUANA_CHANGE account

**CURL TO REPRODUCE THE ISSUE**:

curl --url "http://127.0.0.1:7778" --data "{\"agent\":\"bitcoinrpc\",\"method\":\"encryptwallet\",\"passphrase\":\"testingaccount\"}"
curl --url "http://127.0.0.1:7778" --data "{\"method\":\"setaccount\",\"params\":[\"RQK4mc7ZySXtQ6EweC4r2fcCdBTvsZqDc6\", \"setaccount\"]}"
curl --url "http://127.0.0.1:7778" --data "{\"agent\":\"bitcoinrpc\",\"method\":\"getaddressesbyaccount\",\"account\":\"setaccout\"}"
here you will see that RQK4mc7ZySXtQ6EweC4r2fcCdBTvsZqDc6 wouldn't associate with setaccount,
by re-running the setaccount rpc would associate new address to same account(setaccount) but still not the address(RQK4mc7ZySXtQ6EweC4r2fcCdBTvsZqDc6)  we want to associate

**Comment by jl777** [comment]
pushed fix

**Comment by jl777** [comment]
this has been fixed
