### ISSUE TITLE
change account isn't being created automatically

### ISSUE THREAD

**Issue by kashifali007** [jl777/SuperNET#57]
change account isn't being created automatically and remaining amount from the transaction is disappeared. 

here is the attached snapshot of transaction that I did.
![remainingamount](https://cloud.githubusercontent.com/assets/16662663/17489783/26ac4fac-5db9-11e6-9aee-96a08226c01b.png)

the remaining amount 0.9996 has lost due to no change account.

**Comment by jl777** [comment]
pushed a fix to just use the main address as the change account

**Comment by jl777** [comment]
this has been fixed
