### ISSUE TITLE
rates rpc causing crash when it's executed simultaneously

### ISSUE THREAD

**Issue by kashifali007** [jl777/SuperNET#58]
bitstamp invalid (EUR) or (USD)
({"result":"success","aveprice":1.08955011,"avebid":1.08926023,"bidvol":4.34822444,"aveask":1.08984000,"askvol":2.96437299})  <- aveprice 1.089550
bitcoin invalid (BTC) or (EUR)
btc38 invalid (BTC) or (EUR)
huobi invalid (BTC) or (EUR)
instaforex invalid (BTC) or (EUR)
coinbase invalid (BTC) or (EUR)
lakebtc invalid (BTC) or (EUR)
quadriga invalid (BTC) or (EUR)
okcoin invalid (BTC) or (EUR)
Monitor.btce (BTC EUR) invert.0
bitstamp invalid (BTC) or (EUR)
bitcoin invalid (BTC) or (EUR)
btc38 invalid (BTC) or (EUR)
huobi invalid (BTC) or (EUR)
instaforex invalid (BTC) or (EUR)
coinbase invalid (BTC) or (EUR)
lakebtc invalid (BTC) or (EUR)
quadriga invalid (BTC) or (EUR)
okcoin invalid (BTC) or (EUR)
bitstamp invalid (BTC) or (EUR)
({"result":"success","aveprice":0,"avebid":0,"bidvol":0,"aveask":0,"askvol":0})  <- aveprice 0.000000
bitcoin invalid (BTC) or (USD)
poloniex invalid (BTC) or (USD)
bittrex invalid (BTC) or (USD)
btc38 invalid (BTC) or (USD)
huobi invalid (BTC) or (USD)
instaforex invalid (BTC) or (USD)
bitcoin invalid (BTC) or (USD)
poloniex invalid (BTC) or (USD)
bittrex invalid (BTC) or (USD)
btc38 invalid (BTC) or (USD)
huobi invalid (BTC) or (USD)
instaforex invalid (BTC) or (USD)
**\* stack smashing detected ***: agents/iguana terminated
Aborted (core dumped)
curl --url "http://127.0.0.1:7778" --data "{\"agent\":\"iguana\",\"method\":\"rates\",\"quotes\":[\"BTC/USD\", \"EUR/USD\", \"BTC/EUR\"]}"

curl --url "http://127.0.0.1:7778" --data "{\"agent\":\"iguana\",\"method\":\"rates\",\"quotes\":[\"BTC/USD\", \"EUR/USD\", \"BTC/EUR\"]}"

curl --url "http://127.0.0.1:7778" --data "{\"agent\":\"iguana\",\"method\":\"rates\",\"quotes\":[\"BTC/USD\", \"EUR/USD\", \"BTC/EUR\"]}"

**Comment by jl777** [comment]
pushed fix, along with tests/ratesloop script

**Comment by kashifali007** [comment]
Verified-fixed, closing it

**Comment by kashifali007** [comment]
kashif@ubuntu:~/tests$ ./rates 
{"result":"success","rates":[{"BTC/USD":580.87588012}, {"EUR/USD":0}, {"BTC/EUR":0}],"tag":"10163214240149668708"}
kashif@ubuntu:~/tests$ ./rates 
{"result":"success","rates":[{"BTC/USD":580.87588012}, {"EUR/USD":0}, {"BTC/EUR":0}],"tag":"4023009554718494329"}
kashif@ubuntu:~/tests$ ./rates 
{"result":"success","rates":[{"BTC/USD":583.17996462}, {"EUR/USD":0}, {"BTC/EUR":0}],"tag":"16588775165560055222"}
kashif@ubuntu:~/tests$ ./rates 
{"result":"success","rates":[{"BTC/USD":583.17996462}, {"EUR/USD":0}, {"BTC/EUR":0}],"tag":"5214614756571426229"}
kashif@ubuntu:~/tests$ ./rates 
{"result":"success","rates":[{"BTC/USD":583.17996462}, {"EUR/USD":0}, {"BTC/EUR":0}],"tag":"10000605102764474138"}
kashif@ubuntu:~/tests$ ./rates 
{"result":"success","rates":[{"BTC/USD":583.17996462}, {"EUR/USD":1.11757045}, {"BTC/EUR":0}],"tag":"2060122897881585565"}
kashif@ubuntu:~/tests$ ./rates 
{"result":"success","rates":[{"BTC/USD":583.17500000}, {"EUR/USD":1.11757045}, {"BTC/EUR":0}],"tag":"17694569920717921986"}
kashif@ubuntu:~/tests$ ./rates 
{"result":"success","rates":[{"BTC/USD":583.17500000}, {"EUR/USD":1.11757045}, {"BTC/EUR":0}],"tag":"9790164446709826203"}
kashif@ubuntu:~/tests$ ./rates 
{"result":"success","rates":[{"BTC/USD":583.17500000}, {"EUR/USD":1.11757045}, {"BTC/EUR":0}],"tag":"4945971255073063220"}
kashif@ubuntu:~/tests$ ./rates 
{"result":"success","rates":[{"BTC/USD":583.17500000}, {"EUR/USD":1.11757045}, {"BTC/EUR":519.78202889}],"tag":"263699812619114609"}
kashif@ubuntu:~/tests$ ./rates 
{"result":"success","rates":[{"BTC/USD":583.17500000}, {"EUR/USD":1.11757045}, {"BTC/EUR":519.78202889}],"tag":"10957114935597515437"}
kashif@ubuntu:~/tests$ ./rates 
{"result":"success","rates":[{"BTC/USD":583.17854925}, {"EUR/USD":1.11757045}, {"BTC/EUR":519.78202889}],"tag":"18228986856577131753"}
kashif@ubuntu:~/tests$ ./rates 
{"result":"success","rates":[{"BTC/USD":583.17854925}, {"EUR/USD":1.11757045}, {"BTC/EUR":519.78202889}],"tag":"16532030220063894134"}
kashif@ubuntu:~/tests$ ./rates 
{"result":"success","rates":[{"BTC/USD":583.17996680}, {"EUR/USD":1.11757045}, {"BTC/EUR":519.78202889}],"tag":"10966065747592875885"}
kashif@ubuntu:~/tests$ ./rates 
{"result":"success","rates":[{"BTC/USD":583.17854925}, {"EUR/USD":1.11757045}, {"BTC/EUR":519.78202889}],"tag":"522303798439106952"}
kashif@ubuntu:~/tests$ ./rates 
{"result":"success","rates":[{"BTC/USD":583.17854925}, {"EUR/USD":1.11757045}, {"BTC/EUR":519.78202889}],"tag":"10771853468545461258"}
kashif@ubuntu:~/tests$ ./rates 
{"result":"success","rates":[{"BTC/USD":583.17854925}, {"EUR/USD":1.11757045}, {"BTC/EUR":519.78202889}],"tag":"16015361895208499832"}
kashif@ubuntu:~/tests$ ./rates 
{"result":"success","rates":[{"BTC/USD":583.17854925}, {"EUR/USD":1.11757045}, {"BTC/EUR":519.78202889}],"tag":"6409484940209362527"}
kashif@ubuntu:~/tests$ ./rates 
{"result":"success","rates":[{"BTC/USD":583.17854925}, {"EUR/USD":1.11757045}, {"BTC/EUR":519.78202889}],"tag":"4268924119742929099"}
