### ISSUE TITLE
KomodoPlatform repo shouldn't be a fork anymore

### ISSUE THREAD

**Issue by ns408** [jl777/SuperNET#598]
Currently https://github.com/KomodoPlatform/KomodoPlatform is a fork of https://github.com/jl777/SuperNET.

- You can't search for strings in a fork in github. 
- _And from branding perspective, it may make sense for the primary repo of the project to not be a fork._

Solution: https://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository

**Comment by jl777** [comment]
I dont control KomodoPlatform, maybe you put this issue in the wrong repo?
