### ISSUE TITLE
WebSocket sends invalid JSON

### ISSUE THREAD

**Issue by lukechilds** [jl777/SuperNET#642]
All the WebSocket messages have an invalid JSON character at the end of the string (probably EOF char?). I'm not sure if this is your code or possibly something done by nanomsg?

So I can't just read the byte array from the WebSocket and parse it as JSON, the parser will throw errors.

Instead I need to read the byte array, parse it as a UTF-8 string, remove the last char from the string, then parse the new string as JSON.

I've got this working now with this workaround, but if you're able to remove the invalid ending char that would make my code a lot simpler.

**Comment by jl777** [comment]
pushed fix, to jl777 branch

**Comment by lukechilds** [comment]
Sorted, thanks
