### ISSUE TITLE
Realtime events: `method ` vs `method2`

### ISSUE THREAD

**Issue by lukechilds** [jl777/SuperNET#644]
I've noticed some messages have just a `method` property, while others have `method` and `method2`. As far as I can see `method2` is always the same as `method`.

- What is the difference between `method` and `method2`?
- Is there ever a case where they could differ?
- Why is `method2` sometimes set and sometimes undefined?

**Comment by jl777** [comment]
if you are not on an LP node, method and method2 should always be the same, unless some strange error happens.

commands that are broadcast to the network add a method2 field, so if it has a method2 field, it is most likely a broadcasted command. if not, then it was locally generated

**Comment by lukechilds** [comment]
Thanks
