### ISSUE TITLE
Socket not sending queueid back with response

### ISSUE THREAD

**Issue by lukechilds** [jl777/SuperNET#659]
I may be misunderstanding how the `queueid`s were supposed to work, but it was my understanding we could send an HTTP request with a non zero `queueid` and the socket would send a message when it had been processed with the corresponding `queueid` attached so we could match it up to the request.

However I don't seem to be getting a `queueid` property on any of the socket messages responding to HTTP calls.

e.g sending:

```js
{"queueid":2,"method":"electrum","coin":"KMD","ipaddr":"electrum1.cipig.net","port":10001}
```

I get the following response over the socket:

```js
{"ipaddr":"electrum1.cipig.net","port":10001,"result":"success"}
```

Also, we're getting the invalid ending char on these messages like we had on the other messages before. Are you able to remove the ending char and add the queueid to the response so we can pair them up with the requests?

Built mm from latest commit in dev branch: 207238fb9c9590b5f1faa0add49c7b601e0ec399

**Comment by jl777** [comment]
it seems I goofed up some git merge and it reverted some changes.
added them back, plz try again

**Comment by lukechilds** [comment]
Apologies for delay, just checked this and although you are now passing back a queueid you seem to passing it back inside the `result` object

e.g I'm now getting:

```js
{"queueid":0,"result":{"queueid":2,"method":"electrum","coin":"KMD","ipaddr":"electrum1.cipig.net","port":10001}}
```

When I think it should be:

```js
{"queueid":2,"result":{"method":"electrum","coin":"KMD","ipaddr":"electrum1.cipig.net","port":10001}}
```

**Comment by lukechilds** [comment]
I've just noticed, since that fix you seem to be passing back the original request rather than the response.

**Comment by lukechilds** [comment]
Correct response should be:

```js
{"queueid":2,"result":{"ipaddr":"electrum1.cipig.net","port":10001,"result":"success"}}
```

**Comment by jl777** [comment]
sorry about that. have no idea how I could have messed that up so bad. pushed fix to jl777 branch

**Comment by lukechilds** [comment]
Haha, soooo close, but now the invalid ending char has creeped back in. Are you able to trim that off? Then we should be sorted 🍾

```
{"queueid":2,"result":{"ipaddr":"electrum1.cipig.net","port":10001,"result":"success"}}
```

**Comment by jl777** [comment]
pushed fix

**Comment by lukechilds** [comment]
Resolved, thanks.
