### ISSUE TITLE
Specify WebSocket port

### ISSUE THREAD

**Issue by lukechilds** [jl777/SuperNET#665]
Currently you're allowing us to specify a custom port for mm to listen on. This allows us to make sure we have a free port and can spawn mm, otherwise it'll fail to start and out GUI won't work.

However the WebSocket always listens on port `5555`. Would it be possible for us to pass a port that we know to be free to mm for it to bind to for WebSocket traffic?

So instead of this:

```js
{method: 'getendpoint'}
```

We could issue this:

```js
{method: 'getendpoint', port: 1234}
```

And mm would open the ws connection on port `1234`. The original command should still work and it would just bind to `5555` as normal.

This is will avoid breaking our app if port `5555` is already in use by another process.

**Comment by lukechilds** [comment]
Or if you can do the free port check internally so we know that:

```js
{method: 'getendpoint'}
```

Will always work and return us an available port.

That would be ideal. But if that's too much work on your end we can do the check ourselves and pass it through.

**Comment by jl777** [comment]
good idea. if the port requested is inuse, you will get an error and have to use a different port.
I will add "port" field to getendpoint

**Comment by jl777** [comment]
pushed version with support for "port" field in getendpoint, it will use that to bind the endpoint.
only one such endpoint is supported, so the first getendpoint that succeeds will be the endpoint for that session. default is 5555

**Comment by lukechilds** [comment]
Sounds good, will test tomorrow.

**Comment by lukechilds** [comment]
This appears to have introduced a bug where mm always thinks the port is in use so I can no longer connect to the websocket:

```
$ curl 'http://127.0.0.1:49707/' --data-binary '{"queueid":0,"method":"getendpoint"}'
{"error":"Address already in use","err":-1,"socket":12}

$ curl 'http://127.0.0.1:49707/' --data-binary '{"queueid":0,"method":"getendpoint","port":5555}'
{"error":"Address already in use","err":-1,"socket":12}

$ curl 'http://127.0.0.1:49707/' --data-binary '{"queueid":0,"method":"getendpoint","port":1234}'
{"error":"Address already in use","err":-1,"socket":12}
```

Ports 5555 and 1234 are definitely free.

**Comment by jl777** [comment]
found bug, fixed

**Comment by lukechilds** [comment]
Resolved, thanks!
