### ISSUE TITLE
Inconsistent aliceid between tradestatus and socket events

### ISSUE THREAD

**Issue by lukechilds** [jl777/SuperNET#727]
When you place a buy order you get the output of the `tradestatus` command with the trade you just placed in the pending property.

The trade object looks like this:

```js
{
  alice:"KMD",
  aliceid:17131556477456941000,
  base:"CHIPS",
  basevalue:0.71455733,
  bob:"CHIPS",
  expiration:1522316065,
  quoteid:0,
  rel:"KMD",
  relvalue:0.10001,
  requestid:0,
  timeleft:60,
  tradeid:319616257,
}
```

However, when we get updates on that same trade over the socket the `aliceid` is different. This is how the same trade is represented in a socket message:

```
{
  aliceid:"17131556477456941057",
  base:"CHIPS",
  destaddr:"RQm8BNygniNVqVPRYXEosznRZ7uEiooqSm",
  desthash:"2632d12cd16572b7f45ce0ec3cf92d6beac9a2f53ca3971afbc90dbf6a16344d",
  destsatoshis:"10001000",
  desttxfee:"1000",
  desttxid:"bfed7179966d0fdb5b677b2f539fb7841a79552361a3a4c56cb93ec767084ec9",
  destvout:0,
  etomicdest:"",
  etomicsrc:"",
  feetxid:"5d70d983084c318d2d3beba3976412abeb3cd3710122106f415f018296caf41c",
  feevout:1,
  gui:"hyperdex",
  method:"request",
  price:0.13998037,
  pubkey:"0000000000000000000000000000000000000000000000000000000000000000",
  rel:"KMD",
  satoshis:"71455733",
  timestamp:1522316005,
  tradeid:319616257,
  txfee:"10000",
}
```

Notice instead of `17131556477456941000` `aliceid` is now `"17131556477456941057"`

It's converted from a number into a string and the last two digits change from `00` to `57`.

**Comment by jl777** [comment]
good catch!
pushed fix to jl777 branch

**Comment by lukechilds** [comment]
Yep, works fine now, we get the string version from both APIs.

Thanks for the quick fix!

**Comment by jl777** [comment]
thanks for finding it. i searched and it looks like out of all the conversions it was the only one that was wrong (i hope)

**Comment by lukechilds** [comment]
No problem. Any chance you could ping me when this change makes it into a new release in `dev`?

We're on `Marketmaker 0.1 27771` but I'd like to wait for `27772` or newer before committing a newer bin to our codebase.

**Comment by jl777** [comment]
ping
its in dev branch

**Comment by lukechilds** [comment]
Perfect, thanks!
