### ISSUE TITLE
Electrum balances not showing properly

### ISSUE THREAD

**Issue by lukechilds** [jl777/SuperNET#833]
This looks like it is unrelated to the new perf improvements you pushed to dev, I'm getting this problem in BarterDEX Marketmaker v1.0.164.

I got some Doge sent to my address (thanks @imylomylo) which has definitely confirmed:

https://dogechain.info/address/DLd2e833VJUDJVCpowFFLEcpfzAwTz2sv8

However `markermaker` doesn't show me having any Doge balance in the response to the `portfolio` command. It's been about 20 mins since the TX was sent.

I thought it might be a cache issue and triggering `listunspent` would fix it but that didn't work:

```js
_api.debug({method: 'listunspent', coin: 'DOGE', address: 'DLd2e833VJUDJVCpowFFLEcpfzAwTz2sv8'})
// => []
```

Also I thought `balance` would do directly through to the electrum server but that didn't work either:

```js
_api.debug({method: 'balance', coin: 'DOGE', address: 'DLd2e833VJUDJVCpowFFLEcpfzAwTz2sv8'})
// => {result: "success", coin: "DOGE", address: "DLd2e833VJUDJVCpowFFLEcpfzAwTz2sv8", balance: 0}
```

But if I directly connect to the same Electrum server and query it, I get the correct balance:

```
$ telnet electrum1.cipig.net 10060
Trying 13.230.86.115...
Connected to electrum1.cipig.net.
Escape character is '^]'.
{ "id": 1, "method":"blockchain.address.get_balance", "params":["DLd2e833VJUDJVCpowFFLEcpfzAwTz2sv8"] }
{"jsonrpc": "2.0", "result": {"confirmed": 30100000000, "unconfirmed": 0}, "id": 1}
```

**Comment by jl777** [comment]
pushed fix

**Comment by lukechilds** [comment]
Thanks, that's fixed it!

@artemii235 Can we get a new build?

**Comment by artemii235** [comment]
@lukechilds Sure, going to merge changes to my repo now.

**Comment by artemii235** [comment]
@lukechilds Done: https://github.com/artemii235/SuperNET/releases/tag/v1.0.168

**Comment by lukechilds** [comment]
@artemii235 Thanks!
