### ISSUE TITLE
rates api crash

### ISSUE THREAD

**Issue by pbca26** [jl777/SuperNET#96]
FATAL ERROR OKCOIN.(https://www.okcoin.com/api/v1/depth.do?symbol=btc_usd) only supports USD
DDxKZ8XjzoVmc6EezVcfSt6QFn3h5ZJFnZ DBazrFDtCktURyUErds6mVZriA1wuykcnf DJ7JWV2JNM6jgvMyDSCSFSDAdNqVSPWRZs D9TBR5BmFDLXbsAsbzVztG4VeKyK5ePksJ
FATAL ERROR OKCOIN.(https://www.okcoin.com/api/v1/depth.do?symbol=btc_usd) only supports USD

**Comment by jl777** [comment]
is this the only error with rates? the URL is working now.

**Comment by pbca26** [comment]
so far yes
the problem is that iguana crashed when that url failed to fetch
maybe a rare case but i think worth looking at in future

**Comment by jl777** [comment]
actually there was an exit in case OK coin had error. that seems a bit too strict, so I removed it
